#!/bin/bash

export PATH=$(pwd)/bin:$PATH
if [ ! -f current_instances ]; then
  create-vms
  echo "Sleep 60 seconds for waiting VMs to become 'running'"
  sleep 60
fi
gen-hosts
COUNT=1
KEYPAIR=$(ls *.pem)
HOST=$(cat dns | awk '{ print $3 }')
MASTER=$(head -n1 dns | awk '{ print $3 }')
for i in $HOST; do 
  scp -i ${KEYPAIR} hosts lib/* ubuntu@${i}:.
  ssh -i ${KEYPAIR} ubuntu@${i} "printf \"hdp%02d\" $COUNT > hostname ; sudo mv hostname /etc/hostname; sudo hostname -F /etc/hostname ; sudo mv hosts /etc/hosts ; sudo locale-gen zh_TW.UTF-8"
  if [ "${i}" == "${MASTER}" ]; then
    ssh -i ${KEYPAIR} ubuntu@${i} sudo bash -x /home/ubuntu/install-cm5-master.sh
  else
    ssh -i ${KEYPAIR} ubuntu@${i} sudo bash -x /home/ubuntu/install-cm5-worker.sh
  fi
  ssh -i ${KEYPAIR} ubuntu@${i} sudo bash -x /home/ubuntu/new-user > /dev/null
  COUNT=$((COUNT+1))
done
