CREATE DATABASE user01;
CREATE DATABASE user02;
CREATE DATABASE user03;
CREATE DATABASE user04;
CREATE DATABASE user05;
CREATE DATABASE user06;
CREATE DATABASE user07;
CREATE DATABASE user08;
CREATE DATABASE user09;
CREATE DATABASE user10;
CREATE DATABASE user11;
CREATE DATABASE user12;
CREATE DATABASE user13;
CREATE DATABASE user14;
CREATE DATABASE user15;
CREATE DATABASE user16;
CREATE DATABASE user17;
CREATE DATABASE user18;
CREATE DATABASE user19;
CREATE DATABASE user20;
CREATE DATABASE user21;
CREATE DATABASE user22;
CREATE DATABASE user23;
CREATE DATABASE user24;
CREATE DATABASE user25;
CREATE DATABASE user26;
CREATE DATABASE user27;
CREATE DATABASE user28;
CREATE DATABASE user29;
CREATE DATABASE user30;
CREATE LOGIN user01 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user02 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user03 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user04 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user05 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user06 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user07 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user08 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user09 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user10 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user11 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user12 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user13 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user14 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user15 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user16 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user17 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user18 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user19 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user20 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user21 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user22 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user23 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user24 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user25 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user26 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user27 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user28 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user29 WITH PASSWORD = 'sqoop@etu';
CREATE LOGIN user30 WITH PASSWORD = 'sqoop@etu';
use user01; EXEC sp_changedbowner 'user01';
use user02; EXEC sp_changedbowner 'user02';
use user03; EXEC sp_changedbowner 'user03';
use user04; EXEC sp_changedbowner 'user04';
use user05; EXEC sp_changedbowner 'user05';
use user06; EXEC sp_changedbowner 'user06';
use user07; EXEC sp_changedbowner 'user07';
use user08; EXEC sp_changedbowner 'user08';
use user09; EXEC sp_changedbowner 'user09';
use user10; EXEC sp_changedbowner 'user10';
use user11; EXEC sp_changedbowner 'user11';
use user12; EXEC sp_changedbowner 'user12';
use user13; EXEC sp_changedbowner 'user13';
use user14; EXEC sp_changedbowner 'user14';
use user15; EXEC sp_changedbowner 'user15';
use user16; EXEC sp_changedbowner 'user16';
use user17; EXEC sp_changedbowner 'user17';
use user18; EXEC sp_changedbowner 'user18';
use user19; EXEC sp_changedbowner 'user19';
use user20; EXEC sp_changedbowner 'user20';
use user21; EXEC sp_changedbowner 'user21';
use user22; EXEC sp_changedbowner 'user22';
use user23; EXEC sp_changedbowner 'user23';
use user24; EXEC sp_changedbowner 'user24';
use user25; EXEC sp_changedbowner 'user25';
use user26; EXEC sp_changedbowner 'user26';
use user27; EXEC sp_changedbowner 'user27';
use user28; EXEC sp_changedbowner 'user28';
use user29; EXEC sp_changedbowner 'user29';
use user30; EXEC sp_changedbowner 'user30';
ALTER LOGIN user01 WITH DEFAULT_DATABASE = user01;
ALTER LOGIN user02 WITH DEFAULT_DATABASE = user02;
ALTER LOGIN user03 WITH DEFAULT_DATABASE = user03;
ALTER LOGIN user04 WITH DEFAULT_DATABASE = user04;
ALTER LOGIN user05 WITH DEFAULT_DATABASE = user05;
ALTER LOGIN user06 WITH DEFAULT_DATABASE = user06;
ALTER LOGIN user07 WITH DEFAULT_DATABASE = user07;
ALTER LOGIN user08 WITH DEFAULT_DATABASE = user08;
ALTER LOGIN user09 WITH DEFAULT_DATABASE = user09;
ALTER LOGIN user10 WITH DEFAULT_DATABASE = user10;
ALTER LOGIN user11 WITH DEFAULT_DATABASE = user11;
ALTER LOGIN user12 WITH DEFAULT_DATABASE = user12;
ALTER LOGIN user13 WITH DEFAULT_DATABASE = user13;
ALTER LOGIN user14 WITH DEFAULT_DATABASE = user14;
ALTER LOGIN user15 WITH DEFAULT_DATABASE = user15;
ALTER LOGIN user16 WITH DEFAULT_DATABASE = user16;
ALTER LOGIN user17 WITH DEFAULT_DATABASE = user17;
ALTER LOGIN user18 WITH DEFAULT_DATABASE = user18;
ALTER LOGIN user19 WITH DEFAULT_DATABASE = user19;
ALTER LOGIN user20 WITH DEFAULT_DATABASE = user20;
ALTER LOGIN user21 WITH DEFAULT_DATABASE = user21;
ALTER LOGIN user22 WITH DEFAULT_DATABASE = user22;
ALTER LOGIN user23 WITH DEFAULT_DATABASE = user23;
ALTER LOGIN user24 WITH DEFAULT_DATABASE = user24;
ALTER LOGIN user25 WITH DEFAULT_DATABASE = user25;
ALTER LOGIN user26 WITH DEFAULT_DATABASE = user26;
ALTER LOGIN user27 WITH DEFAULT_DATABASE = user27;
ALTER LOGIN user28 WITH DEFAULT_DATABASE = user28;
ALTER LOGIN user29 WITH DEFAULT_DATABASE = user29;
ALTER LOGIN user30 WITH DEFAULT_DATABASE = user30;
