SHOW DATABASES;
DROP DATABASE IF EXISTS user00;
DROP DATABASE IF EXISTS user01;
DROP DATABASE IF EXISTS user02;
DROP DATABASE IF EXISTS user03;
DROP DATABASE IF EXISTS user04;
DROP DATABASE IF EXISTS user05;
DROP DATABASE IF EXISTS user06;
DROP DATABASE IF EXISTS user07;
DROP DATABASE IF EXISTS user08;
DROP DATABASE IF EXISTS user09;
DROP DATABASE IF EXISTS user10;
DROP DATABASE IF EXISTS user11;
DROP DATABASE IF EXISTS user12;
DROP DATABASE IF EXISTS user13;
DROP DATABASE IF EXISTS user14;
DROP DATABASE IF EXISTS user15;
DROP DATABASE IF EXISTS user16;
DROP DATABASE IF EXISTS user17;
DROP DATABASE IF EXISTS user18;
DROP DATABASE IF EXISTS user19;
DROP DATABASE IF EXISTS user20;
DROP DATABASE IF EXISTS user21;
DROP DATABASE IF EXISTS user22;
DROP DATABASE IF EXISTS user23;
DROP DATABASE IF EXISTS user24;
DROP DATABASE IF EXISTS user25;
DROP DATABASE IF EXISTS user26;
DROP DATABASE IF EXISTS user27;
DROP DATABASE IF EXISTS user28;
DROP DATABASE IF EXISTS user29;
DROP DATABASE IF EXISTS user30;
CREATE DATABASE user00;
CREATE DATABASE user01;
CREATE DATABASE user02;
CREATE DATABASE user03;
CREATE DATABASE user04;
CREATE DATABASE user05;
CREATE DATABASE user06;
CREATE DATABASE user07;
CREATE DATABASE user08;
CREATE DATABASE user09;
CREATE DATABASE user10;
CREATE DATABASE user11;
CREATE DATABASE user12;
CREATE DATABASE user13;
CREATE DATABASE user14;
CREATE DATABASE user15;
CREATE DATABASE user16;
CREATE DATABASE user17;
CREATE DATABASE user18;
CREATE DATABASE user19;
CREATE DATABASE user20;
CREATE DATABASE user21;
CREATE DATABASE user22;
CREATE DATABASE user23;
CREATE DATABASE user24;
CREATE DATABASE user25;
CREATE DATABASE user26;
CREATE DATABASE user27;
CREATE DATABASE user28;
CREATE DATABASE user29;
CREATE DATABASE user30;
SHOW DATABASES;
GRANT ALL ON user00.* TO 'user00'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user01.* TO 'user01'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user02.* TO 'user02'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user03.* TO 'user03'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user04.* TO 'user04'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user05.* TO 'user05'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user06.* TO 'user06'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user07.* TO 'user07'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user08.* TO 'user08'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user09.* TO 'user09'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user10.* TO 'user10'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user11.* TO 'user11'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user12.* TO 'user12'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user13.* TO 'user13'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user14.* TO 'user14'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user15.* TO 'user15'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user16.* TO 'user16'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user17.* TO 'user17'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user18.* TO 'user18'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user19.* TO 'user19'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user20.* TO 'user20'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user21.* TO 'user21'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user22.* TO 'user22'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user23.* TO 'user23'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user24.* TO 'user24'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user25.* TO 'user25'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user26.* TO 'user26'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user27.* TO 'user27'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user28.* TO 'user28'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user29.* TO 'user29'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT ALL ON user30.* TO 'user30'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user00'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user01'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user02'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user03'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user04'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user05'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user06'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user07'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user08'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user09'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user10'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user11'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user12'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user13'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user14'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user15'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user16'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user17'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user18'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user19'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user20'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user21'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user22'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user23'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user24'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user25'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user26'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user27'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user28'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user29'@'%' IDENTIFIED BY 'sqoop@etu';
GRANT SELECT ON test.* TO 'user30'@'%' IDENTIFIED BY 'sqoop@etu';
FLUSH PRIVILEGES;
USE test;
SHOW TABLES;
DROP TABLE IF EXISTS test.mysql_data;
CREATE TABLE test.mysql_data(id int primary key, name varchar(50));
SHOW TABLES;
INSERT INTO test.mysql_data VALUES (1, 'Hello');
INSERT INTO test.mysql_data VALUES (2, 'World');
SELECT * FROM test.mysql_data;
DROP TABLE IF EXISTS test.nyse_daily;
CREATE TABLE test.nyse_daily (exchange varchar(10), symbol varchar(10), date DATE, open float, high float, low float, close float, volume int, adj_close float);
SHOW TABLES;
